name: Deployment pipeline

on:
  push: 
    branches:
      - release

jobs: 
  check-bats-version:
    runs-on: ubuntu-latest
    env:
      KEY_JKS: ${{ secrets.KEY_JKS }}
      KEY_PATH: "upload-keystore.jks"
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
      KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
      SECRETS_FILE_CONTENT: ${{ secrets.SECRETS_FILE_CONTENT }}
      GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
      FASTFILE: ${{ secrets.FASTFILE }}
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'
      - name: Create key file
        run: |
          echo $KEY_JKS | base64 -di > upload-keystore.jks
      - name: Decode base64 secrets
        run: |
          echo $SECRETS_FILE_CONTENT | base64 -di > lib/secrets.dart
          echo $GOOGLE_SERVICES | base64 -di > android/app/google-services.json
          echo $KEY_PROPERTIES | base64 -di > android/key.properties
          echo $FASTFILE | base64 -di > android/fastlane/Fastfile
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle       