name: Firebase App Distribution CI/CD # disable this to save storage
  
on:
  push:
    branches: 
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env: 
      KEY_JKS: ${{ secrets.KEY_JKS }}
      KEY_PATH: "upload-keystore.jks"
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
      SECRETS_FILE_CONTENT: ${{ secrets.SECRETS_FILE_CONTENT }}
      KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
      GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
      FASTLANE_SERVICES: ${{ secrets.FASTLANE_SERVICES }}
      FASTFILE: ${{ secrets.FASTFILE }}
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '12.x'
      - name: Create key file
        run: |
          echo $KEY_JKS | base64 -di > upload-keystore.jks
      - name: Decode base64 secrets
        run: |
          echo $SECRETS_FILE_CONTENT | base64 -di > lib/secrets.dart
          echo $GOOGLE_SERVICES | base64 -di > android/app/google-services.json
          echo $FASTLANE_SERVICES | base64 -di > android/fastlane-service-account.json
          echo $KEY_PROPERTIES | base64 -di > android/key.properties
          echo $FASTFILE | base64 -di > android/fastlane/Fastfile
      - uses: subosito/flutter-action@v1
        with: 
          flutter-version: '3.0.0'
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi
      - run: flutter build apk --debug
      - run: flutter build appbundle    
      - name: Run Firebase App Distribution
        uses: maierj/fastlane-action@v1.4.0
        with: 
          lane: upload_firebase
          subdirectory: android


